### ISSUE TITLE
Adding a pipeline file example notebook

### ISSUE THREAD

**Issue by jlvdb** [LSSTDESC/rail_yaw#12]
Since the yet_another_wizz wrapper is composed of five stages, I would like to include a `pipeline.yaml` file that can reproduce the currently existing notebook `examples/full_example.ipynb`.

I have created a simple notebook that is supposed to generate the pipeline file and then execute it. However I'm struggling to even get the first stage to connect to its input data: https://github.com/LSSTDESC/rail_yaw/blob/9dc44159c7ba38411c55302a5221380243d6bfcc/examples/pipeline.ipynb

When running the generated pipeline file, get this error, but I do not understand what I am doing wrong:
> KeyError: 'cache_ref failed to get data by handle data_ref, associated to data'

**Comment by eacharles** [comment]
see the branch I added.   Basically, you can used DataHandles to establish the connections between stages, but you need to be consistent by using them all the way through.   In your notebook you made the input data in memory and didn't use a DataHandle to wrap it and that was causing the problem you saw.

**Comment by jlvdb** [comment]
Fixes will be addressed in #16
